### PR TITLE
Allow forcing (non-)interactive session

### LINKED ISSUE #3: `askpass()` in RStudio Rmd on Windows
Just returns `NULL` without a dialog, at least on R-devel and win 2022. It aborted my Windows 8.1 in VirtualBox, but that's probably a different issue.

Do reproduce create a new Rmd, and insert a chunk like this:
````
```{r}
askpass::askpass()
```
````

and then save it and click the Knit button.

### PR DESCRIPTION
**Pull request by gaborcsardi**
Closes #3.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
@jeroen Do you want me to add some test cases? I can use mockery to cover the various situations.

**Comment by jeroen** [comment]
No I think that's fine, unless you really find it interesting yourself. This tool is very difficult to test automatically because it is so system dependent and requires user input

**Comment by gaborcsardi** [comment]
Sure, but this single feature is easy to test if you mock the actual `askpass_windows()` etc functions. Anyway, it is fairly straightforward, so hopefully I did not mess it up. :)

**Comment by gaborcsardi** [comment]
Thanks for merging, btw.!

**Comment by jeroen** [comment]
But it would be super helpful if you can manually test if the thing works on your win2022 box, and if you can reproduce the hang for credentials

**Comment by gaborcsardi** [comment]
Yeah, it works fine. I tried this:

````
```{r}
withr::with_options(
  c(rlib_interactive = TRUE),
  askpass::askpass()
)
```
````

and for the original keyring usecase:

````
```{r}
withr::with_options(
  c(rlib_interactive = TRUE),
  keyring::key_get("serv", "user", keyring = "new")
)
```
````

I'll try the credentials vignette in a sec.

**Comment by gaborcsardi** [comment]
credentials works fine on R-hub's builder FWIW: https://artifacts.r-hub.io/credentials_1.3.1.tar.gz-c6f9bede9203459a82f565254822f87c/

**Comment by jeroen** [comment]
Yes I think I found the problem already. It is caused by a new git credential manager for windows, which does not seem to allow to inject credentials non-interactively like I do here:

https://github.com/r-lib/credentials/blob/dd6c37a54d0355b66705e8bdca2fb491734c674c/vignettes/intro.Rmd#L79-L83

And therefore the subsequent `git_credential_ask()` now prompts for credentials.

**Comment by gaborcsardi** [comment]
IDK, I installed the latest git, which has manager-core, and it still works fine.

**Pull request merged**
